import { Dealership, TransitVehicle, VesselManifestRow } from "./types";

export const mockDealers: Dealership[] = [
  {
    id: "d1",
    business_name: "Ridgeway Auto Yard",
    physical_location: "Ngong Road, Nairobi",
    kra_pin: "P0512345678A",
    whatsapp_contact: "254712345001",
    is_premium_partner: true,
    rating_score: 4.8,
    created_at: "2026-01-10T00:00:00Z",
  },
  {
    id: "d2",
    business_name: "Portside Motors",
    physical_location: "Mombasa Road, Nairobi",
    kra_pin: "P0598765432B",
    whatsapp_contact: "254712345002",
    is_premium_partner: false,
    rating_score: 4.5,
    created_at: "2026-01-12T00:00:00Z",
  },
  {
    id: "d3",
    business_name: "Kiambu Road Imports",
    physical_location: "Kiambu Road, Nairobi",
    kra_pin: "P0533221144C",
    whatsapp_contact: "254712345003",
    is_premium_partner: false,
    rating_score: 4.6,
    created_at: "2026-01-14T00:00:00Z",
  },
];

export const mockVehicles: TransitVehicle[] = [
  {
    id: "v1",
    dealer_id: "d1",
    vehicle_title: "2019 Mazda CX-5 Kuro Edition",
    car_make: "Mazda",
    car_model: "CX-5",
    year_of_manufacture: 2019,
    cif_cost_kes: 2650000,
    kra_duty_estimated: 525000,
    vessel_identifier: "MOL Grandeur",
    estimated_arrival_date: "2026-09-05",
    current_transit_status: "On Water",
    chassis_masked_identifier: "K3F2",
    vehicle_hero_image: "/vehicles/cx5.jpg",
    listing_status: "Active",
    review_status: "Approved",
    price_hidden: false,
    is_direct_foreign_listing: false,
    created_at: "2026-08-01T00:00:00Z",
    dealer: mockDealers[0],
  },
  {
    id: "v2",
    dealer_id: "d2",
    vehicle_title: "2020 Toyota Vitz Hybrid F",
    car_make: "Toyota",
    car_model: "Vitz",
    year_of_manufacture: 2020,
    cif_cost_kes: 1180000,
    kra_duty_estimated: 235000,
    vessel_identifier: "Hoegh Tracer",
    estimated_arrival_date: "2026-09-08",
    current_transit_status: "On Water",
    chassis_masked_identifier: "T9L1",
    vehicle_hero_image: "/vehicles/vitz.jpg",
    listing_status: "Active",
    review_status: "Approved",
    price_hidden: false,
    is_direct_foreign_listing: false,
    created_at: "2026-08-03T00:00:00Z",
    dealer: mockDealers[1],
  },
  {
    id: "v3",
    dealer_id: "d3",
    vehicle_title: "2018 Toyota Land Cruiser Prado TX-L",
    car_make: "Toyota",
    car_model: "Prado",
    year_of_manufacture: 2018,
    cif_cost_kes: 5200000,
    kra_duty_estimated: 950000,
    vessel_identifier: "Sakura Leader",
    estimated_arrival_date: "2026-08-27",
    current_transit_status: "Clearing",
    chassis_masked_identifier: "P7B4",
    vehicle_hero_image: "/vehicles/prado.jpg",
    listing_status: "Active",
    review_status: "Approved",
    price_hidden: false,
    is_direct_foreign_listing: false,
    created_at: "2026-07-28T00:00:00Z",
    dealer: mockDealers[2],
  },
  {
    id: "v4",
    dealer_id: "d1",
    vehicle_title: "2019 Nissan Note e-Power",
    car_make: "Nissan",
    car_model: "Note",
    year_of_manufacture: 2019,
    cif_cost_kes: 1350000,
    kra_duty_estimated: 260000,
    vessel_identifier: "NYK Orion",
    estimated_arrival_date: "2026-08-25",
    current_transit_status: "Docked",
    chassis_masked_identifier: "N4D8",
    vehicle_hero_image: "/vehicles/note.jpg",
    listing_status: "Active",
    review_status: "Approved",
    price_hidden: false,
    is_direct_foreign_listing: false,
    created_at: "2026-08-02T00:00:00Z",
    dealer: mockDealers[0],
  },
  {
    id: "v5",
    dealer_id: "d2",
    vehicle_title: "2020 Toyota Fielder Hybrid",
    car_make: "Toyota",
    car_model: "Fielder",
    year_of_manufacture: 2020,
    cif_cost_kes: 1750000,
    kra_duty_estimated: 340000,
    vessel_identifier: "MOL Grandeur",
    estimated_arrival_date: "2026-09-05",
    current_transit_status: "On Water",
    chassis_masked_identifier: "F2X6",
    vehicle_hero_image: "/vehicles/fielder.jpg",
    listing_status: "Active",
    review_status: "Approved",
    price_hidden: false,
    is_direct_foreign_listing: false,
    created_at: "2026-08-05T00:00:00Z",
    dealer: mockDealers[1],
  },
  {
    id: "v6",
    dealer_id: "d3",
    vehicle_title: "2019 Honda Vezel Hybrid Z",
    car_make: "Honda",
    car_model: "Vezel",
    year_of_manufacture: 2019,
    cif_cost_kes: 2150000,
    kra_duty_estimated: 410000,
    vessel_identifier: "Hoegh Tracer",
    estimated_arrival_date: "2026-09-08",
    current_transit_status: "On Water",
    chassis_masked_identifier: "V8H3",
    vehicle_hero_image: "/vehicles/vezel.jpg",
    listing_status: "Active",
    review_status: "Approved",
    price_hidden: false,
    is_direct_foreign_listing: false,
    created_at: "2026-08-06T00:00:00Z",
    dealer: mockDealers[2],
  },
];

export const mockManifestBoard: VesselManifestRow[] = [
  { vessel_identifier: "MOL Grandeur", status: "On Water", eta_label: "11 days", unit_count: 14 },
  { vessel_identifier: "Hoegh Tracer", status: "On Water", eta_label: "14 days", unit_count: 9 },
  { vessel_identifier: "NYK Orion", status: "Docked", eta_label: "Arrived", unit_count: 22 },
  { vessel_identifier: "Sakura Leader", status: "Clearing", eta_label: "2 days", unit_count: 6 },
];
